In [3]:
import pandas as pd
import scipy.io as spio
import numpy as np
import csv
import Sav

In [9]:
df = pd.read_spss('C:/Users/hi/Downloads/20.500.12236_12316/kor_data_19990012.sav')
df

,id,area,area1,sex,age,q1,q2,q3,q3_1,q3_2a1,...,q16_3,q16_4,q16_5,q17,q18,q18_1,occu,religion,income,educ
0,2.0,°æ±âµµ½ÃºÎ,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,¿©ÀÚ,28.0,3.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´çÀÏ³¯,ºÎ¸ð´Ô´ì,NaN,ÁÖºÎ,¾ø´Ù,200.0,16.0
1,3.0,°æ±âµµ±ººÎ,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,¿©ÀÚ,51.0,4.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´çÀÏ³¯,ÀÚ±âÁý,NaN,ÁÖºÎ,ÃµÁÖ±³,¾ø´Ù,9.0
2,5.0,°æ±âµµ±ººÎ,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,¿©ÀÚ,56.0,4.0,ºÎºÎ¿Í »ì°í ÀÖ´Ù,Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,´Ù¸¥ °¡Á·ÀÌ ÀÌ°÷À¸·Î ¿À´Ï±î,Ãß¼® µÚ ÇÑ°¡ÇÒ ¶§,ÀÚ±âÁý,NaN,ÁÖºÎ,±âµ¶±³,60.0,9.0
3,7.0,¼­¿ï,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,¿©ÀÚ,65.0,4.0,"ÇÒ¾Æ¹öÁö, ÇÒ¸Ó´Ï¿Í °°ÀÌ »ì°í ÀÖ´Ù(È®´ë°¡Á·)",Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,´Ù¸¥ °¡Á·ÀÌ ÀÌ°÷À¸·Î ¿À´Ï±î,¼º¹¦ ¾ÈÇÑ´Ù,ÀÚ±âÁý,NaN,ÁÖºÎ,¾ø´Ù,70.0,8.0
4,8.0,¼­¿ï,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,¿©ÀÚ,60.0,2.0,ºÎºÎ¿Í »ì°í ÀÖ´Ù,Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,´Ù¸¥ °¡Á·ÀÌ ÀÌ°÷À¸·Î ¿À´Ï±î,¼º¹¦ ¾ÈÇÑ´Ù,Å«´ì,NaN,ÁÖºÎ,ºÒ±³,100.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1367,1007.0,±¤ÁÖ ºÏ±¸,±¤ÁÖ,³²ÀÚ,37.0,3.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,ÀÖ¾ú´Ù,1¹ø,8¿ù,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´çÀÏ³¯,ÀÚ±âÁý,NaN,5ÀÎ¹Ì¸¸ ¼Ò±Ô¸ð°æ¿µ,¾ø´Ù,°íÁ¤¼öÀÔ ¾ø´Ù,16.0
1368,704.0,±¤ÁÖ ³²±¸,±¤ÁÖ,¿©ÀÚ,22.0,4.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,ÀÖ¾ú´Ù,1¹ø,7¿ù,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´çÀÏ³¯,Å«´ì,NaN,"È¸»ç¿ø, ÀºÇà¿ø",±âµ¶±³,200.0,16.0
1369,518.0,±¤ÁÖ ºÏ±¸,±¤ÁÖ,¿©ÀÚ,29.0,4.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,Æ¯º°È÷ ÈÞ°¡ ±â°£ÀÌ ¾ø´Ù,NaN,NaN,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´çÀÏ³¯,ºÎ¸ð´Ô´ì,NaN,ÁÖºÎ,¾ø´Ù,150.0,12.0
1370,562.0,±¤ÁÖ ¼­±¸,±¤ÁÖ,¿©ÀÚ,22.0,6.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,ÀÖ¾ú´Ù,1¹ø,8¿ù,...,NaN,NaN,°íÇâÀÌ ÀÌ°÷ÀÌ´Ï±î,Ãß¼® ´ÙÀ½³¯,ÀÚ±âÁý,NaN,"¾à»ç,°£È£»ç",¾ø´Ù,¸ð¸£°Ú´Ù,15.0
1371,1152.0,´ë±¸,±¤ÁÖ ¿Ü ´Ù¸¥Áö¿ª,³²ÀÚ,20.0,4.0,ºÎºÎ¿Í ¹ÌÈ¥ÀÎ ÀÚ³à°¡ °°ÀÌ »ê´Ù,¾ø¾ú´Ù,NaN,NaN,...,NaN,NaN,ÀÏ ¶§¹®¿¡ ½Ã°£ÀÌ ¾ø¾î¼­,Ãß¼® ´çÀÏ³¯,Å«´ì,NaN,¹Ý¼÷·Ã°ø,ÃµÁÖ±³,150.0,13.0

In [13]:
import savReaderWriter 
import numpy as np

reader_np = savReaderWriter.SavReaderNp('C:/Users/hi/Downloads/20.500.12236_12316/kor_data_19990012.sav')
array = reader_np.to_structured_array("outfile.dat") 
np.savetxt("outfile2.csv", array, delimiter=",")
reader_np.close()

In [10]:
raw_data = spss.SavReader('largefile.sav', returnHeader = True, ioUtf8=True)

NameError: name 'spss' is not defined

In [14]:
from savReaderWriter import SavReader

In [29]:
raw_data = SavReader('C:/Users/hi/Downloads/20.500.12236_12316/kor_data_19990012.sav', returnHeader = True, ioUtf8=True)
raw_data_list = list(raw_data)
data = pd.DataFrame(raw_data_list)
data_vac = data.rename(columns=data.loc[0]).iloc[1:]
data_vac

,id,area,area1,sex,age,q1,q2,q3,q3_1,q3_2a1,...,q16_3,q16_4,q16_5,q17,q18,q18_1,occu,religion,income,educ
1,2.0,11.0,2.0,2.0,28.0,3.0,2.0,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,3.0,0.0,52.0,6.0,200.0,16.0
2,3.0,12.0,2.0,2.0,51.0,4.0,2.0,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,2.0,0.0,52.0,4.0,0.0,9.0
3,5.0,12.0,2.0,2.0,56.0,4.0,1.0,3.0,0.0,0.0,...,0.0,0.0,6.0,85.0,2.0,0.0,52.0,3.0,60.0,9.0
4,7.0,1.0,2.0,2.0,65.0,4.0,4.0,3.0,0.0,0.0,...,0.0,0.0,6.0,88.0,2.0,0.0,52.0,6.0,70.0,8.0
5,8.0,1.0,2.0,2.0,60.0,2.0,1.0,3.0,0.0,0.0,...,0.0,0.0,6.0,88.0,4.0,0.0,52.0,1.0,100.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1368,1007.0,34.0,1.0,1.0,37.0,3.0,2.0,1.0,1.0,8.0,...,0.0,0.0,1.0,0.0,2.0,0.0,31.0,6.0,8888.0,16.0
1369,704.0,33.0,1.0,2.0,22.0,4.0,2.0,1.0,1.0,7.0,...,0.0,0.0,1.0,0.0,4.0,0.0,21.0,3.0,200.0,16.0
1370,518.0,34.0,1.0,2.0,29.0,4.0,2.0,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,3.0,0.0,52.0,6.0,150.0,12.0
1371,562.0,32.0,1.0,2.0,22.0,6.0,2.0,1.0,1.0,8.0,...,0.0,0.0,1.0,71.0,2.0,0.0,2.0,6.0,9999.0,15.0
1372,1152.0,4.0,2.0,1.0,20.0,4.0,2.0,2.0,0.0,0.0,...,0.0,0.0,2.0,0.0,4.0,0.0,43.0,4.0,150.0,13.0

In [34]:
raw_data = SavReader('kor_data_19990010.sav', returnHeader = True, ioUtf8=True)
raw_data_list = list(raw_data)
data = pd.DataFrame(raw_data_list)
data_gen = data.rename(columns=data.loc[0]).iloc[1:]
data_gen

,id,area,area1,sex,age,q1,q2,q3,q4,q4_1,...,q15_22,q16,q17,q18,q19,q20,occu,religion,income,educ
1,1224.0,32.0,1.0,2.0,39.0,4.0,93.0,62.0,2.0,0.0,...,1.0,5.0,88.0,1.0,1.0,1.0,54.0,4.0,9999.0,12.0
2,1014.0,11.0,2.0,1.0,46.0,6.0,999.0,63.0,2.0,0.0,...,1.0,40.0,0.0,2.0,1.0,9.0,45.0,3.0,250.0,9.0
3,267.0,34.0,1.0,2.0,29.0,4.0,241.0,181.0,1.0,2.0,...,1.0,40.0,3.0,1.0,2.0,9.0,52.0,3.0,200.0,16.0
4,10.0,1.0,2.0,1.0,30.0,4.0,0.0,85.0,2.0,0.0,...,1.0,25.0,10.0,1.0,9.0,9.0,34.0,4.0,130.0,12.0
5,38.0,2.0,2.0,1.0,48.0,5.0,64.0,83.0,2.0,0.0,...,3.0,20.0,10.0,2.0,2.0,2.0,21.0,6.0,250.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1368,264.0,35.0,1.0,1.0,30.0,4.0,180.0,16.0,2.0,0.0,...,2.0,66.0,5.0,1.0,2.0,2.0,42.0,6.0,125.0,12.0
1369,13.0,11.0,2.0,2.0,23.0,5.0,65.0,999.0,2.0,0.0,...,1.0,20.0,5.0,2.0,3.0,3.0,21.0,6.0,9999.0,14.0
1370,1494.0,1.0,2.0,1.0,60.0,3.0,362.0,63.0,2.0,0.0,...,3.0,3.0,2.0,1.0,1.0,2.0,2.0,1.0,0.0,16.0
1371,1253.0,2.0,2.0,1.0,35.0,6.0,999.0,999.0,2.0,0.0,...,9.0,0.0,0.0,4.0,1.0,1.0,31.0,1.0,120.0,12.0
1372,644.0,3.0,2.0,2.0,66.0,8.0,81.0,888.0,2.0,0.0,...,1.0,0.0,0.0,1.0,9.0,9.0,52.0,4.0,200.0,4.0

In [23]:
data1 = pd.get_dummies(data)

In [24]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 1 to 1372
Columns: 2531 entries, id_1.0 to educ_99.0
dtypes: uint8(2531)
memory usage: 3.3 MB

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 1 to 1372
Data columns (total 73 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        1372 non-null   object
 1   area      1372 non-null   object
 2   area1     1372 non-null   object
 3   sex       1372 non-null   object
 4   age       1372 non-null   object
 5   q1        1372 non-null   object
 6   q2        1372 non-null   object
 7   q3        1372 non-null   object
 8   q3_1      1372 non-null   object
 9   q3_2a1    1372 non-null   object
 10  q3_2a2    1372 non-null   object
 11  q3_3a1    1372 non-null   object
 12  q3_3a2    1372 non-null   object
 13  q3_2b1    1372 non-null   object
 14  q3_2b2    1372 non-null   object
 15  q3_3b1    1372 non-null   object
 16  q3_3b2    1372 non-null   object
 17  q3_2c1    1372 non-null   object
 18  q3_2c2    1372 non-null   object
 19  q3_3c1    1372 non-null   object
 20  q3_3c2    1372 non-null   object
 21  q4        1372 non-null   object
 22  q4_1a     1372 non-null   object
 23  q4_1b     1372 non-null   object
 24  q4_2      1372 non-null   object
 25  q4_3      1372 non-null   object
 26  q4_4      1372 non-null   object
 27  q5        1372 non-null   object
 28  q6        1372 non-null   object
 29  q7        1372 non-null   object
 30  q7_1      1372 non-null   object
 31  q8_1      1372 non-null   object
 32  q8_2      1372 non-null   object
 33  q8_3      1372 non-null   object
 34  q8_4      1372 non-null   object
 35  q8_5      1372 non-null   object
 36  q9_1      1372 non-null   object
 37  q9_2      1372 non-null   object
 38  q10       1372 non-null   object
 39  q10_1     1372 non-null   object
 40  q11       1372 non-null   object
 41  q11_1     1372 non-null   object
 42  q12       1372 non-null   object
 43  q13       1372 non-null   object
 44  q14       1372 non-null   object
 45  q14_1     1372 non-null   object
 46  q14_2     1372 non-null   object
 47  q15_1     1372 non-null   object
 48  q15_2     1372 non-null   object
 49  q15_3     1372 non-null   object
 50  q15_4     1372 non-null   object
 51  q15_5     1372 non-null   object
 52  q15_6     1372 non-null   object
 53  q15_7     1372 non-null   object
 54  q15_8     1372 non-null   object
 55  q15_9     1372 non-null   object
 56  q15_10    1372 non-null   object
 57  q15_11    1372 non-null   object
 58  q15_12    1372 non-null   object
 59  q15_13    1372 non-null   object
 60  q16       1372 non-null   object
 61  q16_1     1372 non-null   object
 62  q16_2     1372 non-null   object
 63  q16_3     1372 non-null   object
 64  q16_4     1372 non-null   object
 65  q16_5     1372 non-null   object
 66  q17       1372 non-null   object
 67  q18       1372 non-null   object
 68  q18_1     1372 non-null   object
 69  occu      1372 non-null   object
 70  religion  1372 non-null   object
 71  income    1372 non-null   object
 72  educ      1372 non-null   object
dtypes: object(73)
memory usage: 782.6+ KB

In [36]:
data_gen.to_csv('1999 전국민 일반 csv.csv')