In [1]:
import time
from IPython.display import Image
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler # 표준화(평균을 기준)
from sklearn.preprocessing import MinMaxScaler # 정규화(정해진 규칙 기준, mix-max기준)
from sklearn.datasets import load_iris
# cross_val_score: 다양한 샘플링으 ㄹ해서 여러번 테스트 --> 평균치를 구해본다.!
from sklearn.metrics import *
%matplotlib inline

# 주요 라이브러리 import

from matplotlib import rc, font_manager
import matplotlib.font_manager as fm


# 디렉토리 및 파일 이름에 맞추어 변경
font_location = '../NanumGothic.ttf'
font_name = fm.FontProperties(fname=font_location).get_name()
rc('font', family=font_name)
import scipy.io as spio


import pyreadstat

FileNotFoundError: [Errno 2] No such file or directory: '/Users/syshin/Desktop/Himedia/Himedia_project/문화체육관광부/NanumGothic.ttf'

In [ ]:
import seaborn as sns

In [ ]:
df, meta = pyreadstat.read_sav('../../(원자료) 2020년 국민여행조사_국내여행.sav') ##데이터.sav 경로 지정!!!!

In [ ]:
df.shape ## shape 확인

In [ ]:
##input 년도에 여행한 사람만 추출하기 전 확인
year = 2020 ##년도
df.iloc[50:100,1:15][df['D_TRA1_SYEAR']==year]

In [ ]:
df['D_TRA1_SYEAR'].value_counts()

In [ ]:
##year 년도에 여행한 사람만 추출
df = df[df['D_TRA1_SYEAR']==year]

In [ ]:
## 관광/휴양 이 포함되지 않는 row 제거
df = df[(df['SA1_1']!=0) | (df['SA1_2']!=0.0) | (df['SA1_4']!=0)]

In [ ]:
## 추천도, 재방문의사 보통이상만 추출
df = df[(df['A12']>=3) & (df['A13']>=3)]
df

In [ ]:
## 1차 필요컬럼
columns_list = [
 'D_TRA1_SYEAR',
 'D_TRA1_S_Day',
 'D_TRA1_COST',
 'D_TRA1_ONE_COST',
 'D_TRA1_VAC',
 'D_TRA1_1_SMONTH',
 'D_TRA1_1_SPOT',
 'D_TRA1_1_Q6',
 'D_TRA1_2_SMONTH',
 'D_TRA1_2_SPOT',
 'D_TRA1_2_Q6',
 'D_TRA1_3_SMONTH',
 'D_TRA1_3_SPOT',
 'D_TRA1_3_Q6',
 'D_TRA1_4_SMONTH',
 'D_TRA1_4_SPOT',
 'D_TRA1_4_Q6',
 'D_TRA1_5_SMONTH',
 'D_TRA1_5_SPOT',
 'D_TRA1_5_Q6',
 'D_TRA1_6_SMONTH',
 'D_TRA1_6_SPOT',
 'D_TRA1_6_Q6',
 'D_TRA1_7_SMONTH',
 'D_TRA1_7_SPOT',
 'D_TRA1_7_Q6',
 'D_TRA1_8_SMONTH',
 'D_TRA1_8_SPOT',
 'D_TRA1_8_Q6',
 'D_TRA1_9_SMONTH',
 'D_TRA1_9_SPOT',
 'D_TRA1_9_Q6',
 'D_TRA1_10_SMONTH',
 'D_TRA1_10_SPOT',
 'D_TRA1_10_Q6',
 'D_TRA2_S_Day',
 'D_TRA2_COST',
 'D_TRA2_ONE_COST',
 'D_TRA2_VAC',
 'D_TRA2_1_SMONTH',
 'D_TRA2_1_SPOT',
 'D_TRA2_1_Q6',
 'D_TRA2_2_SMONTH',
 'D_TRA2_2_SPOT',
 'D_TRA2_2_Q6',
 'D_TRA2_3_SMONTH',
 'D_TRA2_3_SPOT',
 'D_TRA2_3_Q6',
 'D_TRA2_4_SMONTH',
 'D_TRA2_4_SPOT',
 'D_TRA2_4_Q6',
 'D_TRA2_5_SMONTH',
 'D_TRA2_5_SPOT',
 'D_TRA2_5_Q6',
 'D_TRA2_6_SMONTH',
 'D_TRA2_6_SPOT',
 'D_TRA2_6_Q6',
 'D_TRA2_7_SMONTH',
 'D_TRA2_7_SPOT',
 'D_TRA2_7_Q6',
 'D_TRA2_8_SMONTH',
 'D_TRA2_8_SPOT',
 'D_TRA2_8_Q6',
 'D_TRA2_9_SMONTH',
 'D_TRA2_9_SPOT',
 'D_TRA2_9_Q6',
 'D_TRA2_10_SMONTH',
 'D_TRA2_10_SPOT',
 'D_TRA2_10_Q6',
 'D_TRA3_S_Day',
 'D_TRA3_COST',
 'D_TRA3_ONE_COST',
 'D_TRA3_VAC',
 'D_TRA3_1_SMONTH',
 'D_TRA3_1_SPOT',
 'D_TRA3_1_Q6',
 'D_TRA3_2_SMONTH',
 'D_TRA3_2_SPOT',
 'D_TRA3_2_Q6',
 'D_TRA3_3_SMONTH',
 'D_TRA3_3_SPOT',
 'D_TRA3_3_Q6',
 'D_TRA3_4_SMONTH',
 'D_TRA3_4_SPOT',
 'D_TRA3_4_Q6',
 'D_TRA3_5_SMONTH',
 'D_TRA3_5_SPOT',
 'D_TRA3_5_Q6',
 'D_TRA3_6_SMONTH',
 'D_TRA3_6_SPOT',
 'D_TRA3_6_Q6',
 'D_TRA3_7_SMONTH',
 'D_TRA3_7_SPOT',
 'D_TRA3_7_Q6',
 'D_TRA3_8_SMONTH',
 'D_TRA3_8_SPOT',
 'D_TRA3_8_Q6',
 'D_TRA3_9_SMONTH',
 'D_TRA3_9_SPOT',
 'D_TRA3_9_Q6',
 'D_TRA3_10_SMONTH',
 'D_TRA3_10_SPOT',
 'D_TRA3_10_Q6',
 'D_TRA4_S_Day',
 'D_TRA4_COST',
 'D_TRA4_ONE_COST',
 'D_TRA4_VAC',
 'D_TRA4_1_SMONTH',
 'D_TRA4_1_SPOT',
 'D_TRA4_1_Q6',
 'D_TRA4_2_SMONTH',
 'D_TRA4_2_SPOT',
 'D_TRA4_2_Q6',
 'D_TRA4_3_SMONTH',
 'D_TRA4_3_SPOT',
 'D_TRA4_3_Q6',
 'D_TRA4_4_SMONTH',
 'D_TRA4_4_SPOT',
 'D_TRA4_4_Q6',
 'D_TRA4_5_SMONTH',
 'D_TRA4_5_SPOT',
 'D_TRA4_5_Q6',
 'D_TRA4_6_SMONTH',
 'D_TRA4_6_SPOT',
 'D_TRA4_6_Q6',
 'D_TRA4_7_SMONTH',
 'D_TRA4_7_SPOT',
 'D_TRA4_7_Q6',
 'D_TRA4_8_SMONTH',
 'D_TRA4_8_SPOT',
 'D_TRA4_8_Q6',
 'D_TRA4_9_SMONTH',
 'D_TRA4_9_SPOT',
 'D_TRA4_9_Q6',
 'D_TRA4_10_SMONTH',
 'D_TRA4_10_SPOT',
 'D_TRA4_10_Q6',
 'D_TRA5_S_Day',
 'D_TRA5_COST',
 'D_TRA5_ONE_COST',
 'D_TRA5_VAC',
 'D_TRA5_1_SMONTH',
 'D_TRA5_1_SPOT',
 'D_TRA5_1_Q6',
 'D_TRA5_2_SMONTH',
 'D_TRA5_2_SPOT',
 'D_TRA5_2_Q6',
 'D_TRA5_3_SMONTH',
 'D_TRA5_3_SPOT',
 'D_TRA5_3_Q6',
 'D_TRA5_4_SMONTH',
 'D_TRA5_4_SPOT',
 'D_TRA5_4_Q6',
 'D_TRA5_5_SMONTH',
 'D_TRA5_5_SPOT',
 'D_TRA5_5_Q6',
 'D_TRA5_6_SMONTH',
 'D_TRA5_6_SPOT',
 'D_TRA5_6_Q6',
 'D_TRA5_7_SMONTH',
 'D_TRA5_7_SPOT',
 'D_TRA5_7_Q6',
 'D_TRA5_8_SMONTH',
 'D_TRA5_8_SPOT',
 'D_TRA5_8_Q6',
 'D_TRA5_9_SMONTH',
 'D_TRA5_9_SPOT',
 'D_TRA5_9_Q6',
 'D_TRA5_10_SMONTH',
 'D_TRA5_10_SPOT',
 'D_TRA5_10_Q6',
 'D_TRA6_S_Day',
 'D_TRA6_COST',
 'D_TRA6_ONE_COST',
 'D_TRA6_VAC',
 'D_TRA6_1_SMONTH',
 'D_TRA6_1_SPOT',
 'D_TRA6_1_Q6',
 'D_TRA6_2_SMONTH',
 'D_TRA6_2_SPOT',
 'D_TRA6_2_Q6',
 'D_TRA6_3_SMONTH',
 'D_TRA6_3_SPOT',
 'D_TRA6_3_Q6',
 'D_TRA6_4_SMONTH',
 'D_TRA6_4_SPOT',
 'D_TRA6_4_Q6',
 'D_TRA6_5_SMONTH',
 'D_TRA6_5_SPOT',
 'D_TRA6_5_Q6',
 'D_TRA6_6_SMONTH',
 'D_TRA6_6_SPOT',
 'D_TRA6_6_Q6',
 'D_TRA6_7_SMONTH',
 'D_TRA6_7_SPOT',
 'D_TRA6_7_Q6',
 'D_TRA6_8_SMONTH',
 'D_TRA6_8_SPOT',
 'D_TRA6_8_Q6',
 'D_TRA6_9_SMONTH',
 'D_TRA6_9_SPOT',
 'D_TRA6_9_Q6',
 'D_TRA6_10_SMONTH',
 'D_TRA6_10_SPOT',
 'D_TRA6_10_Q6',
 'D_TRA7_S_Day',
 'D_TRA7_COST',
 'D_TRA7_ONE_COST',
 'D_TRA7_VAC',
 'D_TRA7_1_SMONTH',
 'D_TRA7_1_SPOT',
 'D_TRA7_1_Q6',
 'D_TRA7_2_SMONTH',
 'D_TRA7_2_SPOT',
 'D_TRA7_2_Q6',
 'D_TRA7_3_SMONTH',
 'D_TRA7_3_SPOT',
 'D_TRA7_3_Q6',
 'D_TRA7_4_SMONTH',
 'D_TRA7_4_SPOT',
 'D_TRA7_4_Q6',
 'D_TRA7_5_SMONTH',
 'D_TRA7_5_SPOT',
 'D_TRA7_5_Q6',
 'D_TRA7_6_SMONTH',
 'D_TRA7_6_SPOT',
 'D_TRA7_6_Q6',
 'D_TRA7_7_SMONTH',
 'D_TRA7_7_SPOT',
 'D_TRA7_7_Q6',
 'D_TRA7_8_SMONTH',
 'D_TRA7_8_SPOT',
 'D_TRA7_8_Q6',
 'D_TRA7_9_SMONTH',
 'D_TRA7_9_SPOT',
 'D_TRA7_9_Q6',
 'D_TRA7_10_SMONTH',
 'D_TRA7_10_SPOT',
 'D_TRA7_10_Q6',
 'D_TRA8_S_Day',
 'D_TRA8_COST',
 'D_TRA8_ONE_COST',
 'D_TRA8_VAC',
 'D_TRA8_1_SMONTH',
 'D_TRA8_1_SPOT',
 'D_TRA8_1_Q6',
 'D_TRA8_2_SMONTH',
 'D_TRA8_2_SPOT',
 'D_TRA8_2_Q6',
 'D_TRA8_3_SMONTH',
 'D_TRA8_3_SPOT',
 'D_TRA8_3_Q6',
 'D_TRA8_4_SMONTH',
 'D_TRA8_4_SPOT',
 'D_TRA8_4_Q6',
 'D_TRA8_5_SMONTH',
 'D_TRA8_5_SPOT',
 'D_TRA8_5_Q6',
 'D_TRA8_6_SMONTH',
 'D_TRA8_6_SPOT',
 'D_TRA8_6_Q6',
 'D_TRA8_7_SMONTH',
 'D_TRA8_7_SPOT',
 'D_TRA8_7_Q6',
 'D_TRA8_8_SMONTH',
 'D_TRA8_8_SPOT',
 'D_TRA8_8_Q6',
 'D_TRA8_9_SMONTH',
 'D_TRA8_9_SPOT',
 'D_TRA8_9_Q6',
 'D_TRA8_10_SMONTH',
 'D_TRA8_10_SPOT',
 'D_TRA8_10_Q6',
 'A1_1',
 'A1_2',
 'A1_3',
 'A2',
 'A4_1',
 'A4_2',
 'A4_3',
 'A5_1',
 'A5_2',
 'A5_3',
 'A5_4',
 'A5_5',
 'A5_6',
 'A5_7',
 'A5_8',
 'A5_9',
 'A5_10',
 'A5_11',
 'A5_12',
 'A5_13',
 'A5_14',
 'A5_15',
 'A5_16',
 'A5_17',
 'A5_18',
 'A5_19',
 'A5_20',
 'A5_21',
 'A7',
 'A7A',
 'A7B_1',
 'A7B_2',
 'A7B_3',
 'A7B_4',
 'A7B_5',
 'A7B_6',
 'A7B_7',
'A8_TOTAL',
 'NA8_1',
 'NA8_TOTAL',
 'NA9A',
 'NA9B',
 'NA9C',
 'NA9D',
 'NA9E',
 'NA9F',
 'NA9G',
 'NA9H',
 'NA9I',
 'A9',
 'NA9',
 'A11',
 'A11A_1',
 'A11A_2',
 'A11A_3',
 'A11A_4',
 'A11A_5',
 'A11A_6',
 'A11A_7',
 'A11A_8',
 'A11A_9',
 'A11A_10',
 'A11A_11',
 'A11A_12',
 'DQ7',
 'BSEX',
 'BAGE',
 'SAGE',
 'BMON',
 'BARA',
 '국내_숙박여부',
 'WT_DOM'

]

In [ ]:
df = df[columns_list]

In [ ]:
df.reset_index(inplace=True)
del df['index']
df

In [ ]:
## 퍼진 컬럼들 압축 과정

## TRA1_1, TRA1_2 등 모든 여행지 파생변수 area로 ,로 구분해서 입력, 
## 여행지 개수 count하여 no_of_place 컬럼에입력
# 1-1 1-2 1-3 1-4 1-5 ... 8-10
# [1,2,3,4,5,6]
sleepnights_list = [] #여행지에서 잔 밤수(박) ex) 1박 2일 = 1
cost_list = [] # 여행비용 <=이후 중복컬럼 생겨서 미사용
area_list = [] # 거주지 
count_list = [] # 여행지 개수 일치확인용 
month_list = [] # 여행 출발 월
accommodation_list = []
for index in df.index:
    sleepnights = ''
    cost = ''
    area = ''
    count = 0
    month = ''
    accommodation = ''
    for i in range (1,9):
        col_sleepnights = 'D_TRA'+str(i)+'_S_Day'       
        col_cost = 'D_TRA'+str(i)+'_COST'        
        try: 
            sleepnights = sleepnights + str(int(df.loc[index,col_sleepnights])) + ','
            cost = cost + str(int(df.loc[index,col_cost])) +','
        except: pass
        for j in range(1,11):

            col_area ='D_TRA'+str(i)+'_'+str(j)+'_SPOT'
            col_month = 'D_TRA'+str(i)+'_'+str(j)+'_SMONTH'
            col_accommodation = 'D_TRA'+str(i)+'_'+str(j)+'_Q6'
            try: 
                area = area + str(int(df.loc[index, col_area])) + ','
                count += 1
            except: pass
            try:
                month = month + str(int(df.loc[index, col_month])) + ','
            except:
                pass
            try:
                accommodation = accommodation + str(int(df.loc[index, col_accommodation])) + ','
            except:
                pass
    try:
        area = area.rstrip(area[-1])
    except:pass
    try:
        sleepnights = sleepnights.rstrip(sleepnights[-1])
    except:pass
    try:
        cost = cost.rstrip(cost[-1])
    except:pass
    try:
        month = month.rstrip(month[-1])
    except:pass
    try:
        accommodation = accommodation.rstrip(accommodation[-1])
    except:pass
    area_list.append(area)
    count_list.append(count)
    month_list.append(month)
    cost_list.append(cost)
    accommodation_list.append(accommodation)
    sleepnights_list.append(sleepnights)

df['area']= area_list
df['no_of_place'] = count_list
df['month'] = month_list
df['cost'] = cost_list
df['sleepnights'] = sleepnights_list
df['accommodation'] = accommodation_list

In [ ]:
## 확인
df[['area', 'no_of_place', 'month', 'cost', 'sleepnights', 'accommodation']]

In [ ]:
## 2차 필요컬럼
columns_list = [
 'D_TRA1_SYEAR',
 'area', 'no_of_place', 'cost', 'sleepnights', 'accommodation',
 'A1_1',
 'A1_2',
 'A1_3',
 'A4_1',
 'A4_2',
 'A4_3',
 'A5_1',
 'A5_2',
 'A5_3',
 'A5_4',
 'A5_5',
 'A5_6',
 'A5_7',
 'A5_8',
 'A5_9',
 'A5_10',
 'A5_11',
 'A5_12',
 'A5_13',
 'A5_14',
 'A5_15',
 'A5_16',
 'A5_17',
 'A5_18',
 'A5_19',
 'A5_20',
 'A5_21',
 'A7',
 'A7A',
 'A7B_1',
 'A7B_2',
 'A7B_3',
 'A7B_4',
 'A7B_5',
 'A7B_6',
 'A7B_7',
 'A9',
 'NA9',
 'A11',
 'A11A_1',
 'A11A_2',
 'A11A_3',
 'A11A_4',
 'A11A_5',
 'A11A_6',
 'A11A_7',
 'A11A_8',
 'A11A_9',
 'A11A_10',
 'A11A_11',
 'A11A_12',
 'DQ7',
 'BSEX',
 'SAGE',
 'BMON',
 'BARA'
]

In [ ]:
df = df[columns_list]

In [ ]:
## 타겟 컬럼 list (미사용포함)
target_rawcol = []
for i in range(1,22):
    target_rawcol.append("A5_"+str(i))
target_rawcol

In [ ]:
# Target값 전처리

# Q5. 다녀오신 여행에서 참여하신 활동은 무엇입니까? 해당되는 항목은 모두 선택해 주십시오.
# column명: A5_1 ~ A5_21
# 전처리 전:
# 자연 및 풍경감상
# 음식관광(지역 맛집 등)
# 야외 위락 및 스포츠, 레포츠 활동
# 역사 유적지 방문
# 테마파크, 놀이시설, 동/식물원 방문
# 휴식/휴양
# 온천/스파
# 쇼핑
# 지역 문화예술/공연/전시시설 관람
# 스포츠 경기관람
# 지역 축제/이벤트참가
# 교육/체험 프로그램 참가
# 종교/성지순례
# 카지노, 경마, 경륜 등
# 시티투터
# 드라마 촬영지 방문
# 유흥/오락
# 가족/친지/친구 방문
# 회의참가/시찰
# 교육/훈련/연수
# 기타

# 전처리 후:
# 1.자연 및 풍경감상
# 2.음식관광(지역 맛집 등)
# 3.야외 위락 및 스포츠, 레포츠 활동
# 4.역사 유적지 방문                                  + 16. 드라마 촬영지 방문
# 5.테마파크, 놀이시설, 동/식물원 방문
# 6.휴식/휴양                                            + 7. 온천/스파
# 8.쇼핑                                                   + 15. 시티투어
# 9.지역 문화예술/공연/전시시설 관람         + 10.스포츠 경기관람, 11.지역 축제/이벤트참가 +12. 교육/체험 프로그램 참가
# 17.유흥/오락                                           +14.카지노, 경마, 경륜 등
# 21.기타

# 삭제할 컬럼
# 13.종교/성지순례
# 18.가족/친지/친구 방문
# 19.회의참가/시찰
# 20.교육/훈련/연수

In [ ]:
# 로우 드랍 할 target
# 13.종교/성지순례 385
# 18.가족/친지/친구 방문 2755
# 19.회의참가/시찰 244
# 20.교육/훈련/연수 185
# 21.기타 89 합:4081
dropcol = ['A5_13','A5_18','A5_19','A5_20', 'A5_21']
intdropcol = [13,18,19,20,21]
## 안쓰는 target row drop (기준 밖 로우들 제거)
for i, col in enumerate(dropcol):
    df = df[df[col] != intdropcol[i]]
## 안쓰는 target column drop
df.drop(columns = dropcol, inplace=True)
df

In [ ]:
target_col = ['A5_1',
 'A5_2',
 'A5_3',
 'A5_4',
 'A5_5',
 'A5_6',
 'A5_7',
 'A5_8',
 'A5_9',
 'A5_10',
 'A5_11',
 'A5_12',
 'A5_14',
 'A5_15',
 'A5_16',
 'A5_17']
target_intlist = [1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17]
print(len(target_intlist), len(target_col))

In [ ]:
df[['no_of_place','A5_1',
 'A5_2',
 'A5_3',
 'A5_4',
 'A5_5',
 'A5_6',
 'A5_7',
 'A5_8',
 'A5_9',
 'A5_10',
 'A5_11',
 'A5_12',
 'A5_14',
 'A5_15',
 'A5_16',
 'A5_17']]

In [ ]:
##타겟 컬럼 압축 과정

##각 타겟 컬럼들안에 값이 있다면 추출, list에 저장
##새 컬럼에 list 삽입

target_list = []
for index in df.index:
    target_beforesplit=''
    for columns in target_col:
        try: 
            target_beforesplit = target_beforesplit + str(int(df.loc[index, columns])) + ','
        except:
            pass
    target_beforesplit = target_beforesplit.rstrip(target_beforesplit[-1])
    target_list.append(target_beforesplit)
target_list
df['target_beforesplit'] = target_list

In [ ]:
## 기존 타겟 컬럼들 drop

## 타겟 컬럼들의 데이터가 압축되어 새 컬럼에 있으니
df.drop(columns=target_col, inplace=True)

In [ ]:
## 교통수단 컬럼들 압축

transportaion_list = []
for index in df.index:
    transportation=''
    for columns in ['A1_1', 'A1_2', 'A1_3']:
        try: 
            transportation = transportation + str(int(df.loc[index, columns])) + ','
        except:
            pass
    transportation = transportation.rstrip(transportation[-1])
    transportaion_list.append(transportation)
transportaion_list
df['transportation'] = transportaion_list

In [ ]:
## 교통 수단 압축 확인
df[['A1_1', 'A1_2', 'A1_3','transportation']].head(60)

In [ ]:
#교통수단 컬럼들 제거
df.drop(columns=['A1_1', 'A1_2', 'A1_3'], inplace=True)

In [ ]:
## 여행지 선택 이유 컬럼 압축
reason_list = []
for index in df.index:
    reason=''
    for columns in ['A4_1', 'A4_2', 'A4_3']:
        try: 
            reason = reason + str(int(df.loc[index, columns])) + ','
        except:
            pass
    reason = reason.rstrip(reason[-1])
    reason_list.append(reason)
transportaion_list
df['reason'] = reason_list

In [ ]:
df.drop(columns=['A4_1', 'A4_2', 'A4_3'], inplace=True)

In [ ]:
## 추가 미사용 컬럼 제거
delete_col = ['A7B_1',
 'A7B_2',
 'A7B_3',
 'A7B_4',
 'A7B_5',
 'A7B_6',
 'A7B_7']

In [ ]:
## 여행자간 관계 컬럼 압축

relationship_list = []
for index in df.index:
    relationship=''
    for columns in delete_col:
        try: 
            relationship = relationship + str(int(df.loc[index, columns])) + ','
        except:
            pass
    try:
        relationship = relationship.rstrip(relationship[-1])
    except:pass
    relationship_list.append(relationship)
relationship_list
df['relationship'] = relationship_list
df[['A7B_1',
 'A7B_2',
 'A7B_3',
 'A7B_4',
 'A7B_5',
 'A7B_6',
 'A7B_7', 'relationship']].head(60)

In [ ]:
## 관계 컬럼 제거

df.drop(columns=delete_col, inplace=True)
df

In [ ]:
## 추가 미사용 컬럼 제거

df.drop(columns=[ 'A11A_1', 'A11A_2',
       'A11A_3', 'A11A_4', 'A11A_5', 'A11A_6', 'A11A_7', 'A11A_8', 'A11A_9',
       'A11A_10', 'A11A_11', 'A11A_12', 'DQ7'], inplace=True)

In [ ]:
## 최종으로 남은 컬럼들 코드에서 명칭으로 컬러명 변경

df.rename(columns = {'D_TRA1_SYEAR' : 'year',
                     'A7' : 'number_of_ppl',
                     'A7A' : 'number_of_children',
                     'A9' : 'cost_total_trip',
                     'NA9': 'cost_total_per_person',
                     'A11' : 'satisfied',

                     'BSEX': 'sex', 
                     'SAGE': 'age', 
                     'BMON': 'month', 
                     'BARA': 'living_area',
                     'area': 'target_area'
                    
                     
                    }, inplace = True)

In [ ]:
df.drop(columns='cost', inplace=True)

In [ ]:
df = df.reset_index()
df

In [ ]:
del df['index']

In [ ]:
df.to_csv("2020_압축버전.csv")

In [ ]:
df

# 카테고리 전처리 ==========================================================================

In [ ]:
df

In [ ]:
## target값 split하여 One-hot encoding
for index in df.index:
  target_list_index = df.loc[index,'target_beforesplit'].split(',')
  for targets in target_list_index:
    for i in [1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17]:
      t_col = 'target_'+str(i)
      if targets == str(i):
        df.loc[index,t_col]= 1

In [ ]:
df[['target_beforesplit', 'target_1', 'target_2', 'target_3',
       'target_4', 'target_5', 'target_6', 'target_7', 'target_8', 'target_9',
       'target_10', 'target_11', 'target_12', 'target_14', 'target_15',
       'target_16', 'target_17']]

In [ ]:
df

In [ ]:
## 여행지 장소 split
for index in df.index:
  target_list_index = df.loc[index,'target_area'].split(',')
  for i, targets in enumerate(target_list_index):
      t_col = 'target_area'+str(i+1)
      df.loc[index,t_col]= targets

In [ ]:
## 14박 이상 잔 row제거
for i in df.index: 
    if sum(list(map(int, df.loc[index, 'sleepnights'].split(',')))) > 14:
        df.drop(index=i, inplace=True)

In [ ]:
## 잔 횟수와(박)과 숙소 일치시키기

## 반복된 숙소 중복제거후 sleepnight당 나올 수 있는 
## accommodation 경우의수 마다 조건으로 처리
## 마지막 예외 제거 : 4row

## 반복된 숫자 줄이는 메서드
def shrink_accom(accom): 
    i = 0
    result = accom
    while i < len(result)-1:
        if result[i] == result[i+1]:
            del result[i]
        else:
            i = i+1
    return result

In [ ]:
for index in df.index: ##당일여행 한번 갔을때: accommodation=0
    accommo_list = []
    try:splitted_nights = list(map(int, df.loc[index, 'sleepnights'].split(','))) ## sleepnights를 int로 split
    except:print("typeerror>>",index)
    if splitted_nights == [0]:
        df.loc[index, 'accommodation'] = 0
    else:
        s = np.count_nonzero(splitted_nights) ## splitted_nights중 0이 아닌 수 count s
        if s == 0: ## 0,0,0 와 같이 0만 있을 때, 0으로 채움            for i in range(len(splitted_nights)):
            for i in range(len(splitted_nights)):
                accommo_list.append(0)
            for i, accommo in enumerate(accommo_list):
                col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                df.loc[index,col_name] = 0
        else:
            splitted_accommo = list(map(int, df.loc[index, 'accommodation'].split(',')))
            # except:print('attributeError>>',index, df.loc[index,'accommodation'])
            shrinked_accommo = shrink_accom(list(map(int, df.loc[index, 'accommodation'].split(',')))) ## 반복된 숫자 줄여줌
            if (s == len(shrinked_accommo)) or (len(shrinked_accommo) == 1):## s와 accommo의 길이가 같을때: s의 수대로 accommo를 곱해준다
                if [len(shrinked_accommo)] == splitted_nights: ## 0미포함
                    for i, accommo in enumerate(shrinked_accommo):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo
                else:    ##0포함
                    j=0
                    for i, nights in enumerate(splitted_nights):
                        if nights == 0:
                            accommo_list.append(0)
                        else:
                            for ni in range(nights):
                                accommo_list.append(shrinked_accommo[j])
                    j+=1
                    for i, accommo in enumerate(accommo_list):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo
            elif s > len(shrinked_accommo): ## s가 accommo의 길이보다 클 때
                if len(list(map(int, df.loc[index, 'accommodation'].split(',')))) == len(splitted_nights):
                    for i, accommo in enumerate(splitted_nights):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo
                    
                else:
                    for i, nights in enumerate(splitted_nights): ## 3,0,1 12,0,1 => 12,12,12,0,1
                        if nights == 0:
                            accommo_list.append(0)
                        else:
                            for ni in range(nights):
                                try:accommo_list.append(shrinked_accommo[i])
                                except:print('indexError>>', index, "s:", s, "s_night:", splitted_nights , 
                                             "slpnight:", df.loc[index, 'sleepnights'], 
                                             "accom", df.loc[index, 'accommodation'], 
                                             "splt_accom:", splitted_accommo)
                    for i, accommo in enumerate(accommo_list):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo 
                
            else: 
                if sum(list(map(int, df.loc[1215, 'sleepnights'].split(',')))) == len(list(map(
                    int, df.loc[index, 'accommodation'].split(',')))): ## [0,0,2] [1,2]
                    j=0
                    for i, nights in enumerate(list(map(int, df.loc[1215, 'sleepnights'].split(',')))): 
                        if nights == 0:
                            accommo_list.append(0)
                        else:
                            for ni in range(nights):
                                accommo_list.append(list(map(int, df.loc[index, 'accommodation'].split(',')))[j])
                                j+=1
                    for i, accommo in enumerate(accommo_list):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo 
                if [len(shrinked_accommo)] == splitted_nights: ## 0미포함
                    for i, accommo in enumerate(shrinked_accommo):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo
                elif sum(list(map(int, df.loc[index, 'sleepnights'].split(',')))) == len(list(map(int, df.loc[index, 'accommodation'].split(',')))):
                    accommo_list = list(map(int, df.loc[index, 'accommodation'].split(',')))
                    for i, accommo in enumerate(accommo_list):
                        col_name = 'accommodation_' + str(i+1) ##dataframe에 입력
                        df.loc[index,col_name] = accommo
                    # print("caught row>>", index, "s:", s, "s_night:", splitted_nights , "slpnight:", df.loc[index, 'sleepnights'], "accom", df.loc[index, 'accommodation'], "shrink_accom:", shrinked_accommo)
                else:
                    print("drop row>>", index, "s:", s, "s_night:", splitted_nights , "slpnight:", df.loc[index, 'sleepnights'], "accom", df.loc[index, 'accommodation'], "shrink_accom:", shrinked_accommo)
                    df.drop(index=index, inplace=True)

In [ ]:
## 컬럼 순서 정리

column_order = ['year', 'target_area', 'no_of_place', 'sleepnights', 'accommodation',
       'number_of_ppl', 'number_of_children', 'cost_total_trip',
       'cost_total_per_person', 'satisfied', 'sex', 'age', 'month',
       'living_area', 'target_beforesplit', 'transportation', 'reason',
       'relationship', 'target_1', 'target_2', 'target_3','target_4','target_5','target_6', 'target_7','target_8', 'target_9','target_10','target_11', 'target_12','target_14', 'target_15','target_16', 'target_17', 
        'target_area1', 'target_area2', 'target_area3',
       'target_area4', 'target_area5', 'target_area6', 'target_area7',
       'target_area8', 'target_area9', 'target_area10', 'target_area11',
       'transportation1', 'transportation2', 'transportation3', 'reason1',
       'reason2', 'reason3', 'accommodation_1', 'accommodation_2',
       'accommodation_3', 'accommodation_4', 'accommodation_5',
       'accommodation_6', 'accommodation_7', 'accommodation_8',
       'accommodation_9', 'accommodation_10', 'accommodation_11',
       'accommodation_12', 'accommodation_13', 'accommodation_14']

In [ ]:
df = df.reindex(columns=column_order)

In [ ]:
df.info()

In [ ]:
df

In [ ]:
df.to_csv('2020_split버전.csv')

# 배포 이후 코딩

In [ ]:
df = pd.read_csv('2020_split버전.csv', encoding='utf-8', index_col=0)
df

In [ ]:
df.columns

In [ ]:
df[['no_of_place','target_beforesplit']]

In [ ]:
df